FROM golang:1.18.4-alpine3.16 AS builder

RUN apk --update add git make openssh

RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.45.2

ARG SSH_PRIVATE_KEY
RUN mkdir -p ~/.ssh && echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa \
    && git helper --global url."git@github.com:".insteadOf https://github.com/ \
    && ssh-keyscan github.com >> ~/.ssh/known_hosts

ENV GO111MODULE on
ENV GOOS linux
ENV CGO_ENABLED 0

EXPOSE 8080